### ISSUE TITLE
运行node enrollAdmin.js时出现TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Nancy-cy** [steakliu/blockchain-trace-fabric#10]
node enrollAdmin.js

/root/blockchain-trace-fabric/blockchain-trace-bcnetwork/webapp/node_modules/@grpc/grpc-js/build/src/call-stream.js:26
const { HTTP2_HEADER_STATUS, HTTP2_HEADER_CONTENT_TYPE, NGHTTP2_CANCEL, } = http2.constants;
                                                                                 ^

TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/root/blockchain-trace-fabric/blockchain-trace-bcnetwork/webapp/node_modules/@grpc/grpc-js/build/src/call-stream.js:26:82)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/blockchain-trace-fabric/blockchain-trace-bcnetwork/webapp/node_modules/@grpc/grpc-js/build/src/channel.js:19:23)
    at Module._compile (module.js:569:30)

**Comment by steakliu** [comment]
请使用node12 ， 我已经更新blockchain-trace-bcnetwork/webapp/package.json里grpc ， fabric-client  fabric-ca-client版本

**Comment by Nancy-cy** [comment]
> 请使用node12 ， 我已经更新blockchain-trace-bcnetwork/webapp/package.json里grpc ， fabric-client fabric-ca-client版本

已解决 感谢
